### PR TITLE
Don't leak x509_certificate_chain rows

### PR DESCRIPTION
**Pull request by Al2Klimov**

### CODE REVIEW

**Comment by Al2Klimov** [comment]
Hint: hide whitespace changes.

**Comment by nilmerg** [comment]
What issue does this fix? What does it affect? Why is it necessary?

**Comment by Al2Klimov** [comment]
It saves lots of disk space.

**Comment by nilmerg** [comment]
20 lines of code and 58 added ones. That's 38 new lines of code. Where does this save disk space?

Well, I guess you need to explain your reasoning better. :thinking:

**Comment by Al2Klimov** [comment]
The disk space is saved on your MySQLd server by re-using existing rows instead of creating new ones on every scan.

**Comment by nilmerg** [comment]
Thanks :wink:

**Pull request merged**
