### PR TITLE
No longer require innodb_large_prefix

### PR DESCRIPTION
**Pull request by lippserd**
/cc @bobapple

### CODE REVIEW

**Comment by lippserd** [comment]
@nilmerg I talked with @bobapple about this and I think it makes sense to have this for version 1.0.0. Could you please have a look?

**Comment by dnsmichi** [comment]
I was waiting for this too, I'll run this in icinga/icinga-vagrant#185 :)

**Comment by lippserd** [comment]
Thanks @nilmerg. Fixed the docs.

**Comment by dnsmichi** [comment]
Works fine inside Vagrant :)

Screen Shot 2019-05-29 at 13 32 31

Screen Shot 2019-05-29 at 13 31 03

**Pull request merged**
